Another test reporter

diff --git a/.github/workflows/dotnet-core.yml b/.github/workflows/dotnet-core.yml
--- a/.github/workflows/dotnet-core.yml
+++ b/.github/workflows/dotnet-core.yml
@@ -22,8 +22,10 @@ jobs:
         run: dotnet build --configuration Release --no-restore
       - name: Test
         run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=TestResults.xml"
-      - name: Publish Unit Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v1
-        if: always()
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
         with:
-          files: tests/**/*.xml
+          name: XUNIT Tests # Name of the check run which will be created
+          path: tests/**/*.xml # Path to test results
+          reporter: dotnet-trx # Format of test results
